---
title: Keuzes maken
hero_image: images/banner.png
description: Laat een gebruiker van je micro:bit programma keuzes maken
version: 1
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Laat je gebruikers keuzes maken
